BaseUrl: http://pamrucinque.com.s3-website-ap-southeast-2.amazonaws.com/
LanguageCode: en-AU
Title: Pam Rucinque
paginate : 5
Copyright : All rights reserved - 2016
canonifyurls : true
theme: casper

params:
  description : Posts in English and Spanish
  cover : images/cover.jpg
  author : Pam Rucinque
  authorlocation : Melbourne, Australia
  #  googleAnalyticsUserID : UA-79101-12
  githubName : pameck
  twitterName : pamrucinque
  RSSLink :
  # facebookName :
  # linkedinName :
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport : als