baseurl: https://pamrucinque.com/
LanguageCode: en-AU
Title: Pam Rucinque
paginate : 5
Copyright : All rights reserved - 2016
DisqusShortname : "pamelarucinque"
theme: casper

params:
  description : Developer * Women-in-Tech and Digital Privacy Advocate
  cover : images/cover3.jpg
  author : Pam Rucinque
  authorlocation : Melbourne, Australia
  googleAnalyticsUserID : UA-81873608-1
  githubName : pameck
  twitterName : pamrucinque
  RSSLink :
  # facebookName :
  linkedinName : pamelarucinqueserna
  flickrName: pamrucinque
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport : false
  logo: images/logo.png